### ISSUE TITLE
[FR] add parameter to default

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#291] opened 2019-07-08 14:58 UTC
please insert the following paramert to the default settings, at this point you have to manualy insert it 

connections: @CONFIGCONNECTION@

Example:
file:
        {
                  active: true
                  target: lib://SERReports
                  mode: DELETEALLFIRST
                  connections: @CONFIGCONNECTION@
        }
hub:
        {
                  active: true
                  mode: DELETEALLFIRST
                  #owner: test
                  connections: @CONFIGCONNECTION@
        }

**Comment by r-hannuschka** [comment] 2019-07-12 06:30
duplicate of #289

**Closed by r-hannuschka** 2019-07-12 06:30 UTC
Labels: duplicate, fr
