### ISSUE TITLE
[FR] new interface for ContentLib template selektion

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#267] opened 2019-06-17 11:24 UTC

**Comment by AlexanderGoerlich** [comment] 2019-06-17 11:25
Please add a button and show a modal window like this:

![image](https://user-images.githubusercontent.com/13659581/59601053-37e20700-9103-11e9-999b-d380d88ef737.png)

**Comment by AlexanderGoerlich** [comment] 2019-06-17 11:27
remove "template output format" input field 

![image](https://user-images.githubusercontent.com/13659581/59601139-74adfe00-9103-11e9-8414-d531db4721da.png)

**Comment by AlexanderGoerlich** [comment] 2019-06-17 11:47
- [ ] create new modal for "Template"
- [ ] add a new buton "seletc template"
- [ ] remove input "template output format"
- [ ] add new checkbox for "template output Password"

**Comment by r-hannuschka** [comment] 2019-06-20 17:09
Duplicate of #148

**Closed by r-hannuschka** 2019-06-20 17:09 UTC
Labels: duplicate, fr
